# Generated by Django 2.2 on 2019-04-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Contactos',
        ),
    ]
