# Generated by Django 2.2 on 2019-04-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190406_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactos',
            options={},
        ),
    ]
